version: '3.3'
services:
wazuh.manager:
image: wazuh/wazuh-manager:4.7.0
ports:
- "1514:1514/udp"
- "1515:1515"
volumes:
- wazuh_data:/var/ossec/data

elasticsearch:
image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
environment:
- discovery.type=single-node
- xpack.security.enabled=false
ports:
- "9200:9200"

kibana:
image: docker.elastic.co/kibana/kibana:7.10.2
ports:
- "5601:5601"
depends_on:
- elasticsearch

volumes:
wazuh_data:
